/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LienzoImagen.java
 *
 * Created on 02-feb-2011, 17:41:07
 */

package jfi.test;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;

/**
 *
 * @author Jesús Chamorro
 */
public class LienzoImagen extends javax.swing.JPanel {
    private BufferedImage img;

    /** Creates new form LienzoImagen */
    public LienzoImagen() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setImage(BufferedImage img){
        this.img = img;
        this.setPreferredSize(new Dimension(img.getWidth(),img.getHeight()));
    }

    public BufferedImage getImage(){
        return(img);
    }

    public void paint(Graphics g){
        super.paint(g);
        if(img!=null) g.drawImage(img,0,0,this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
