/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaImagen.java
 *
 * Created on 02-feb-2011, 17:32:54
 */

package jfi.test;

/**
 *
 * @author Jesús Chamorro
 */
public class VentanaImagen extends javax.swing.JInternalFrame {

    /** Creates new form VentanaImagen */
    public VentanaImagen() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzoImagen = new jfi.test.LienzoImagen();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout lienzoImagenLayout = new javax.swing.GroupLayout(lienzoImagen);
        lienzoImagen.setLayout(lienzoImagenLayout);
        lienzoImagenLayout.setHorizontalGroup(
            lienzoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );
        lienzoImagenLayout.setVerticalGroup(
            lienzoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzoImagen);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public jfi.test.LienzoImagen lienzoImagen;
    // End of variables declaration//GEN-END:variables

}
